### ISSUE TITLE
kakao login 구현 : 최종 ^.^

### ISSUE THREAD

**Issue by StopSoo** [WhatIsMethIs/WhatIsMethIs-App#13]
제가 구현한 카카오 로그인 구현 상태는 다음과 같습니다 !
커밋 메시지 'final kakao login'에서 코드 확인하실 수 있습니닷 :)

https://github.com/WhatIsMethIs/WhatIsMethIs-App/assets/114139700/b77954ff-0d01-46e1-8bf5-72f30625073a

- async - await 설정에 실패 .. 대신 찾은 답안 => 로그인 성공을 통해 'none'에서 'kakao'로 바뀌었을 경우 바로 화면 전환되게 했습니다. 문제 있으면 알려주세요 ! 
<img width="541" alt="Screenshot 2023-09-02 at 22 05 09" src="https://github.com/WhatIsMethIs/WhatIsMethIs-App/assets/114139700/8a18e9e0-68fa-4b05-9af6-5660540c6ae5">
<br><br>

- 의문점 1 : 메인 화면에서 로그인 페이지로 다시 넘어가는 방법은 없는지 ...? 사실 아직 딱히 필요가 없을 것 같기도 .. 
- 의문점 2 : 혹시 애플 로그인 구현됐나요 !? 됐다면 앱 자체 이메일 로그인만 제외하고 애플, 카카오 두 가지인지 여쭤봅니다 ! 얘기했었던 것 같은데 가물가물 ...

**Comment by 220v-K** [comment]
옹 async-await으로 완료 비동기처리 안해도 저렇게 할 수 있으면 괜찮겠네요! 굿입니다
혹시 로그인 버튼을 누르고 로그인에 성공하지 못했을 시에도 LoginPlatform이 변하여 화면이 넘어가지는 않나요? @StopSoo

**Comment by jjunjji** [comment]
의문점 1: 메인 화면 -> 마이페이지 -> 로그아웃  과정을 통해서 로그인 페이지로 갈 수는 있는데 메인화면에서 바로 로그인 페이지로 넘어갈 필요는 없다구 생각해요/

재원시가 말한 거만 확인하면 될 듯용~~

**Comment by StopSoo** [comment]
@220v-K 혹시 몰라서 try-catch문 해놓고 로그인 실패 시 로그인 실패 프린트되게만 해놨어요! 

지금은 이런 식으로 아이디와 비밀번호를 틀리거나 까먹어서 로그인이 안 될 경우,<br>
<img width="327" alt="Screenshot 2023-08-24 at 21 36 36" src="https://github.com/WhatIsMethIs/WhatIsMethIs-App/assets/114139700/0d9d891f-feac-4935-9d71-bfcf831910d8">
<br>
취소 창을 눌러서 다시 로그인 화면으로 돌아오는 경우만 확인해봤는데 아래와 같이 메인 화면으로 안 넘어갑니다 ! <br>
<img width="327" alt="Screenshot 2023-08-24 at 21 36 36" src="https://github.com/WhatIsMethIs/WhatIsMethIs-App/assets/114139700/784027d8-2732-4868-964e-a8f4b6871519">

아마 제 생각에는 .. 로그인됐을 때만 setState 함수가 실행될 테니까 괜찮을 것 같은데요 ?!

**Comment by 220v-K** [comment]
아 짱이에요 수고하셨습니다 ^ㅁ^
